on:
  schedule:
    - cron: '17 22 * * *'  # 每天晚上 22:17（UTC）执行

jobs:
  run:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Run a script
        run: |
          echo "This task runs every day at 22:17 UTC"
          # 在这里添加你想要执行的其他命令